service: saveaclick
provider:
  name: aws
  profile: syac
  region: us-east-1
  runtime: nodejs10.x
  stage: ${opt:stage}
  tags:
    VERSION: ${env:RELEASE_TAG}
  iam:
    role: ${env:IAM_EXECUTION_ROLE_ARN}
    deploymentRole: ${env:IAM_DEPLOYMENT_ROLE_ARN}
  environment:
    ROOT_HOST: ${env:ROOT_HOST}
    REDIS_ENDPOINT: ${env:REDIS_ENDPOINT}
    REDIS_PASSWORD: ${env:REDIS_PASSWORD}
    NODE_ENV: ${env:NODE_ENV}
    REDDIT_CLIENT_ID: ${env:REDDIT_CLIENT_ID}
    REDDIT_CLIENT_SECRET: ${env:REDDIT_CLIENT_SECRET}
custom:
  webpack:
    packager: 'npm' 
    includeModules:
      packagePath: "./package.json"
  # serverless-layers:
  #   dependenciesPath: "./package.json"
  #   functions:
  #     - app
  customDomain:
    certificateArn: ${env:CERTIFICATE_ARN}
    domainName: app.savedyouaclick.org
    basePath: ""
    stage: prod
    createRoute53Record: false

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager
  # - serverless-layers

functions:
  assets:
    handler: index.app
    memorySize: 128
    maximumRetryAttempts: 0
    name: saveaclick-assets
    timeout: 3
    events:
      - http:
          path: /assets
          method: GET
          cors: false
  app:
    handler: index.app
    memorySize: 128
    maximumRetryAttempts: 0
    name: saveaclick-app
    timeout: 25
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: false
